service: skill-tcfm-player

plugins:
  - serverless-plugin-warmup
  - serverless-plugin-tracing

provider:
  name: aws
  tracing: true
  region: ap-northeast-1
  runtime: nodejs8.10
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - Fn::Join:
          - ":"
          -
            - arn:aws:lambda
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - function:${self:service}-${opt:stage, self:provider.stage}-*
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"

custom:
  warmup:
    memorySize: 128

package:
  include:
    - node_modules/

functions:
  main:
    warmup: true
    handler: index.handler
    events:
      - alexaSkill:
          appId: ${env:SKILL_ID}
          enabled: true
  cacheUpdator:
    handler: cacheUpdator.handler
    events:
      - schedule: rate(60 minutes)
